### ISSUE TITLE
Tras cambiar mi usuario, "respuestas a comentarios" no funciona

### ISSUE THREAD

**Issue by rastersoft** [Meneame/meneame.net#3]
He modificado mi nombre de usuario, y al pulsar en el menú de alertas (la "campana" de arriba a la derecha) (por ejemplo porque hay una respuesta a un comentario mío) y luego en "respuestas a comentarios", falla indicando "Usuario inexistente". En la URL veo que intenta ir al nombre de usuario viejo en lugar de al nuevo. Si cambio manualmente en la URL el nombre y pongo el nuevo, aparece la página correcta.

El resto de las opciones del menú de alertas funcionan correctamente, usando el nuevo nombre de usuario.

**Comment by osvid** [comment]
Creo que de alguna manera la URL antigua se queda en en el caché del navegador. Si pruebas a acceder desde otro navegador o borrar el caché debería funcionarte. Supongo que se debería poder solucionar desde el código, pero no lo he mirado nunca.

**Comment by rastersoft** [comment]
Voy a probar lo de la caché, dame un momento...

**Comment by rastersoft** [comment]
Efectivamente, limpiando la caché se soluciona. Gracias!
