### ISSUE TITLE
No puedo comentar ni ver comentarios.

### ISSUE THREAD

**Issue by ghost** [Meneame/meneame.net#51]
Hola, no entiendo muy bien porqué, pero si estoy logueado no me deja ver los comentarios ni escribir comentarios. Pensaba que era tema de algún adblock o algo pero tengo todo desactivado, es más, sino estoy logueado también me deja ver y escribrir comentarios. Lo raro es que en la version de lab.meneame si que me deja ver y escribir con mi usuario.
Alguna ayuda? Gracias
![image](https://user-images.githubusercontent.com/73649669/140045063-fc4689d4-2f6a-4582-8cc8-8abaf5eeb3e2.png)

**Comment by TBouadi** [comment]
También me he fijado que se queda cargando y no sale nada arriba a la derecha
![image](https://user-images.githubusercontent.com/73649669/140045571-d0445cae-b8ab-4d63-a6c0-0465c9e701ca.png)

**Comment by ghost** [comment]
Funciona otra vez, supongo que sería algo puntual
